[package]
name = "sandbox"
version = "1.1.0"
edition = "2018"

[dependencies]
pixels = "0.2"
imgui = "0.4"
imgui-wgpu = { git = "https://github.com/cwfitzgerald/imgui-wgpu-rs", branch = "wgpu-update" }
imgui-winit-support = "0.4"
winit = "0.22"
rand = "0.7"
simdnoise = "3.1"
flume = { version = "0.7", default-features = false }
puffin = "0.2"
puffin-imgui = "0.2"
bytemuck = "1.3"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
