[package]
name = "sandbox"
version = "1.0.0"
edition = "2018"

[features]
video-recording = ["gstreamer", "gstreamer-app", "gstreamer-video", "dirs-next", "humantime", "anyhow"]

[dependencies]
pixels = { git = "https://github.com/parasyte/pixels" }
winit = "0.22"
rand = "0.7"
simdnoise = "3.1"
flume = "0.7"

gstreamer = { version = "0.16", optional = true }
gstreamer-app = { version = "0.16", optional = true }
gstreamer-video = { version = "0.16", optional = true }
dirs-next = { version = "1.0", optional = true }
humantime = { version = "2.0", optional = true }
anyhow = { version = "1.0", optional = true }

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = true
