[package]
name = "sandbox"
version = "1.1.0"
edition = "2018"

[dependencies]
pixels = "0.1"
winit = "0.22"
rand = "0.7"
simdnoise = "3.1"
flume = "0.7"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = true
