[package]
name = "sandbox"
version = "1.2.0"
edition = "2018"

[dependencies]
pixels = { git = "https://github.com/parasyte/pixels" }
imgui = "0.7"
imgui-wgpu = "0.15"
imgui-winit-support = "0.7"
winit = "0.24"
rand = "0.8"
rand_pcg = "0.3"
simdnoise = "3.1"
flume = { version = "0.10", default-features = false }
puffin = "0.4"
puffin-imgui = "0.7"
bytemuck = "1.5"

[profile.dev]
opt-level = 3

[profile.release]
lto = true
