[package]
name = "sandbox"
version = "1.1.0"
edition = "2018"

[dependencies]
pixels = "0.2"
imgui = "0.4"
imgui-wgpu = "0.9"
imgui-winit-support = "0.4"
winit = "0.22"
rand = "0.7"
simdnoise = "3.1"
flume = { version = "0.9", default-features = false }
puffin = "0.3"
puffin-imgui = "0.3"
bytemuck = "1.4"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
